package co.uniquindio.edu.co.trabajoveterinaria20252.Model;

public enum Tratamiento {
    CIRUGIA_DE_CATARATAS,
    TRATAMIENTO_DE_ULCERAS_CORNEALES,
    CIRUGIA_PARA_EXTIRPAR_TUMORES,
    QUIMIOTERAPIA_EN_ANIMALES,
    CIRUGIA_DE_HERNIAS_DE_DISCO,
    TRATAMIENTO_DE_EPILEPSIA,
    ANESTESIA_GENERAL,
    SEDACION,
    TRATAMIENTO_DE_INSUFICIENCIA_CARDIACA,
    COLOCACION_DE_MARCAPASOS
}